a= int(input("give 'a' a number"))
b= int(input("give 'b' a number"))
Sum= a + b
Difference= a - b or b - a
Product= a * b
Quotient_of_the_squares= (a * a) / (b * b)
print("Sum=", Sum)
print("Difference=", Difference)
print("Product=", Product)
print("Quotient of their squares=", Quotient_of_the_squares)